const AmbientSession = require('../models/AmbientSession');

const d = (daysAgo) => new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000);

const sampleSessions = [
  // ── Draft (2) ─────────────────────────────────────────────────────────────
  {
    sessionId: 'ACI-001',
    providerName: 'Dr. John Smith',
    patientId: 'PT-100001',
    patientName: 'James Wilson',
    patientDOB: new Date('1968-03-15'),
    patientInsurance: 'Blue Cross Blue Shield',
    chiefComplaint: 'Chest pain',
    recordingDuration: 210,
    urgencyClassification: 'urgent',
    audioTranscript: 'Patient James Wilson, 56-year-old male, presents with intermittent chest pain over the past three days. Pain is described as pressure-like, 6 out of 10, radiating to the left arm. No diaphoresis. No prior cardiac history. EKG performed in office shows no acute changes. Troponin pending. Vitals stable, BP 138/88, HR 84.',
    clinicalSummary: 'S: 56-year-old male with 3-day history of intermittent pressure-like chest pain, 6/10, radiating to left arm. No diaphoresis or syncope.\nO: BP 138/88, HR 84, RR 16, SpO2 98%. EKG: no acute ST changes. Troponin pending.\nA: Chest pain, etiology unclear — rule out ACS.\nP: Troponin follow-up, cardiology referral pending results.',
    status: 'draft',
    createdAt: d(2),
    updatedAt: d(2),
  },
  {
    sessionId: 'ACI-002',
    providerName: 'Dr. Sarah Chen',
    patientId: 'PT-100003',
    patientName: 'Thomas Brown',
    patientDOB: new Date('1975-07-22'),
    patientInsurance: 'Aetna',
    chiefComplaint: 'Chronic headaches',
    recordingDuration: 145,
    urgencyClassification: 'routine',
    audioTranscript: 'Patient Thomas Brown, 49-year-old male, reports chronic daily headaches for approximately 4 months. Pain is bifrontal, 5 out of 10, worse in the mornings. No visual aura. No nausea or vomiting. Taking OTC ibuprofen with partial relief. Neurological exam grossly intact. Sleep reported as poor.',
    clinicalSummary: 'S: 49-year-old male with 4-month history of chronic daily bifrontal headaches, 5/10, worse in mornings. OTC ibuprofen provides partial relief.\nO: Neuro exam intact. BP 124/78. No papilledema.\nA: Chronic daily headache, possible tension-type vs. medication overuse.\nP: Neurology referral for further evaluation.',
    status: 'draft',
    createdAt: d(1),
    updatedAt: d(1),
  },

  // ── Reviewing (1) ─────────────────────────────────────────────────────────
  {
    sessionId: 'ACI-003',
    providerName: 'Dr. John Smith',
    patientId: 'PT-100002',
    patientName: 'Emily Rodriguez',
    patientDOB: new Date('1990-11-05'),
    patientInsurance: 'UnitedHealth',
    chiefComplaint: 'Blurred vision',
    recordingDuration: 185,
    urgencyClassification: 'urgent',
    audioTranscript: 'Patient Emily Rodriguez, 34-year-old female, presents with sudden onset blurred vision in the right eye, onset 48 hours ago. Denies pain. No floaters or flashes initially but reports a small shadow in peripheral vision since this morning. History of mild myopia. No prior ocular surgery.',
    clinicalSummary: 'S: 34-year-old female with 48-hour history of blurred vision right eye and new peripheral shadow. No pain.\nO: Visual acuity 20/200 right, 20/20 left. Fundoscopic exam limited without dilation. Pupils equal and reactive.\nA: Right eye visual disturbance, possible retinal pathology — urgent ophthalmology evaluation required.\nP: Same-day ophthalmology referral.',
    referralNoteDraft: 'Dear Ophthalmology Colleague,\n\nI am referring Ms. Emily Rodriguez, a 34-year-old female, for urgent evaluation of sudden-onset right eye blurred vision with peripheral shadow of 48-hour duration. Visual acuity is 20/200 OD. Given the acute presentation and concern for possible retinal detachment or other urgent retinal pathology, same-day or next-day evaluation is strongly recommended.\n\nThank you for your prompt attention.\n\nSincerely,\nDr. John Smith',
    urgencyClassification: 'urgent',
    urgencyReason: 'Acute visual loss with peripheral shadow raises concern for retinal detachment requiring same-day ophthalmology evaluation.',
    icdCodes: ['H53.10', 'H33.009', 'H52.10'],
    recommendedSpecialty: 'Ophthalmology',
    status: 'reviewing',
    createdAt: d(3),
    updatedAt: d(1),
  },

  // ── Approved (4) ──────────────────────────────────────────────────────────
  {
    sessionId: 'ACI-004',
    providerName: 'Dr. John Smith',
    patientId: 'PT-100001',
    patientName: 'James Wilson',
    patientDOB: new Date('1968-03-15'),
    patientInsurance: 'Blue Cross Blue Shield',
    chiefComplaint: 'Shortness of breath',
    recordingDuration: 320,
    urgencyClassification: 'urgent',
    audioTranscript: 'Patient James Wilson returns with progressive shortness of breath on exertion over 2 weeks. Now limited to 1 flight of stairs. BNP elevated at 480. Echo ordered. History of hypertension, well controlled on lisinopril. No orthopnea. Mild bilateral ankle edema noted on exam. Crackles bilateral bases.',
    clinicalSummary: 'S: 56-year-old male with 2-week history of progressive dyspnea on exertion, now limited to 1 flight of stairs. Mild bilateral ankle edema.\nO: BP 142/90, HR 92, SpO2 94% on room air. Bilateral basal crackles. 1+ pitting edema ankles. BNP 480 pg/mL.\nA: New onset heart failure with reduced or preserved ejection fraction — cardiology referral warranted.\nP: Echo ordered, cardiology referral initiated, low-sodium diet counseling provided.',
    referralNoteDraft: 'Dear Cardiology Colleague,\n\nI am referring Mr. James Wilson, a 56-year-old male with hypertension, for evaluation of new onset heart failure. He presents with progressive exertional dyspnea, bilateral basal crackles, 1+ ankle edema, and an elevated BNP of 480 pg/mL. An echocardiogram has been ordered. Cardiology evaluation for management and further workup is requested.\n\nThank you,\nDr. John Smith',
    urgencyReason: 'Elevated BNP with clinical signs of heart failure requires urgent cardiology evaluation and echocardiogram.',
    icdCodes: ['I50.9', 'I10', 'R06.09'],
    recommendedSpecialty: 'Cardiology',
    status: 'approved',
    approvedNote: 'Dear Cardiology Colleague,\n\nI am referring Mr. James Wilson, a 56-year-old male with hypertension, for evaluation of new onset heart failure. He presents with progressive exertional dyspnea, bilateral basal crackles, 1+ ankle edema, and an elevated BNP of 480 pg/mL. An echocardiogram has been ordered. Cardiology evaluation for management and further workup is requested.\n\nThank you,\nDr. John Smith',
    reviewedAt: d(4),
    createdAt: d(7),
    updatedAt: d(4),
  },
  {
    sessionId: 'ACI-005',
    providerName: 'Dr. Sarah Chen',
    patientId: 'PT-100004',
    patientName: 'Maria Garcia',
    patientDOB: new Date('1982-09-18'),
    patientInsurance: 'Cigna',
    chiefComplaint: 'Joint pain',
    recordingDuration: 265,
    urgencyClassification: 'routine',
    audioTranscript: 'Patient Maria Garcia, 43-year-old female, with 6-month history of symmetric polyarthritis involving MCPs, PIPs, and wrists bilaterally. Morning stiffness lasting over 2 hours. RF and anti-CCP both positive. ESR 68, CRP 3.2. Radiographs of hands ordered — no erosions yet. No current DMARDs.',
    clinicalSummary: 'S: 43-year-old female with 6-month symmetric polyarthritis — MCPs, PIPs, wrists bilaterally. Morning stiffness >2 hours.\nO: Tender and swollen MCPs/PIPs bilateral. RF positive, anti-CCP positive. ESR 68, CRP 3.2. Hand XR: no erosions.\nA: Seropositive rheumatoid arthritis, early disease.\nP: Rheumatology referral for DMARD initiation.',
    referralNoteDraft: 'Dear Rheumatology Colleague,\n\nI am referring Ms. Maria Garcia, a 43-year-old female, for evaluation and management of newly diagnosed seropositive rheumatoid arthritis. She presents with 6-month symmetric polyarthritis, prolonged morning stiffness, elevated inflammatory markers (ESR 68, CRP 3.2), and positive RF and anti-CCP antibodies. Hand radiographs show no erosions at this time. She has not yet been started on DMARDs and would benefit from prompt rheumatologic management.\n\nThank you,\nDr. Sarah Chen',
    urgencyReason: 'Early seropositive RA requires timely DMARD initiation to prevent joint destruction.',
    icdCodes: ['M05.79', 'M79.3', 'Z13.828'],
    recommendedSpecialty: 'Rheumatology',
    status: 'approved',
    approvedNote: 'Dear Rheumatology Colleague,\n\nI am referring Ms. Maria Garcia, a 43-year-old female, for evaluation and management of newly diagnosed seropositive rheumatoid arthritis. She presents with 6-month symmetric polyarthritis, prolonged morning stiffness, elevated inflammatory markers (ESR 68, CRP 3.2), and positive RF and anti-CCP antibodies. Hand radiographs show no erosions at this time. She has not yet been started on DMARDs and would benefit from prompt rheumatologic management.\n\nThank you,\nDr. Sarah Chen',
    reviewedAt: d(8),
    createdAt: d(12),
    updatedAt: d(8),
  },
  {
    sessionId: 'ACI-006',
    providerName: 'Dr. John Smith',
    patientId: 'PT-100005',
    patientName: 'David Lee',
    patientDOB: new Date('1955-01-30'),
    patientInsurance: 'Medicare',
    chiefComplaint: 'Type 2 diabetes management',
    recordingDuration: 480,
    urgencyClassification: 'routine',
    audioTranscript: 'Patient David Lee, 70-year-old male, established patient with type 2 diabetes. Last HbA1c 9.4% three months ago. Currently on metformin 1000mg twice daily and glipizide 10mg daily. Reports polyuria and polydipsia. Fundoscopic exam shows early non-proliferative diabetic retinopathy. Microalbumin elevated. Feet exam: reduced monofilament sensation bilateral.',
    clinicalSummary: 'S: 70-year-old male with poorly controlled T2DM. HbA1c 9.4%. Polyuria and polydipsia. On metformin + glipizide.\nO: BP 148/92. BG 214 fasting. Fundoscopic: early NPDR bilateral. Microalbumin/Cr ratio elevated. Monofilament: decreased sensation bilateral feet.\nA: Poorly controlled T2DM with early diabetic nephropathy, retinopathy, and peripheral neuropathy.\nP: Endocrinology referral for regimen optimization; ophthalmology and podiatry co-management.',
    referralNoteDraft: 'Dear Endocrinology Colleague,\n\nI am referring Mr. David Lee, a 70-year-old male, for optimization of his type 2 diabetes management. His most recent HbA1c is 9.4% despite metformin and glipizide. He has evidence of early diabetic nephropathy (elevated microalbuminuria), bilateral non-proliferative diabetic retinopathy, and peripheral neuropathy with reduced monofilament sensation. Medication adjustment and comprehensive diabetes management guidance are requested.\n\nThank you,\nDr. John Smith',
    urgencyReason: 'Poorly controlled T2DM with multi-organ complications (nephropathy, retinopathy, neuropathy) requires specialist optimization.',
    icdCodes: ['E11.65', 'E11.319', 'E11.40', 'N18.2'],
    recommendedSpecialty: 'Endocrinology',
    status: 'approved',
    approvedNote: 'Dear Endocrinology Colleague,\n\nI am referring Mr. David Lee, a 70-year-old male, for optimization of his type 2 diabetes management. His most recent HbA1c is 9.4% despite metformin and glipizide. He has evidence of early diabetic nephropathy (elevated microalbuminuria), bilateral non-proliferative diabetic retinopathy, and peripheral neuropathy with reduced monofilament sensation. Medication adjustment and comprehensive diabetes management guidance are requested.\n\nThank you,\nDr. John Smith',
    reviewedAt: d(15),
    createdAt: d(20),
    updatedAt: d(15),
  },
  {
    sessionId: 'ACI-007',
    providerName: 'Dr. John Smith',
    patientId: 'PT-100003',
    patientName: 'Thomas Brown',
    patientDOB: new Date('1975-07-22'),
    patientInsurance: 'Aetna',
    chiefComplaint: 'Abdominal pain',
    recordingDuration: 300,
    urgencyClassification: 'urgent',
    audioTranscript: 'Patient Thomas Brown returns with 3-week history of right upper quadrant abdominal pain, worse after fatty meals. Pain is colicky, 7 out of 10 at peak. One episode of jaundice noted by family last week. LFTs show elevated total bilirubin 2.8 and alkaline phosphatase 320. Ultrasound shows cholelithiasis with CBD dilation to 9mm.',
    clinicalSummary: 'S: 49-year-old male with 3-week RUQ colicky pain worsening post-fatty meals. Episode of jaundice reported.\nO: T 37.4, tenderness RUQ without guarding. Total bilirubin 2.8, ALP 320, ALT 88. US: cholelithiasis, CBD 9mm.\nA: Choledocholithiasis with obstructive jaundice pattern — GI/surgery referral indicated.\nP: GI referral for ERCP evaluation; general surgery consultation for cholecystectomy planning.',
    referralNoteDraft: 'Dear Gastroenterology Colleague,\n\nI am referring Mr. Thomas Brown, a 49-year-old male, for evaluation of likely choledocholithiasis. He presents with 3 weeks of right upper quadrant colicky pain, an episode of clinical jaundice, elevated bilirubin (2.8 mg/dL) and alkaline phosphatase (320 U/L), and ultrasound findings of cholelithiasis with common bile duct dilation to 9mm. ERCP evaluation is recommended. General surgery has also been consulted for cholecystectomy planning.\n\nThank you,\nDr. John Smith',
    urgencyReason: 'Choledocholithiasis with obstructive jaundice pattern and CBD dilation requires timely ERCP evaluation.',
    icdCodes: ['K80.50', 'K83.1', 'R17'],
    recommendedSpecialty: 'Gastroenterology',
    status: 'approved',
    approvedNote: 'Dear Gastroenterology Colleague,\n\nI am referring Mr. Thomas Brown, a 49-year-old male, for evaluation of likely choledocholithiasis. He presents with 3 weeks of right upper quadrant colicky pain, an episode of clinical jaundice, elevated bilirubin (2.8 mg/dL) and alkaline phosphatase (320 U/L), and ultrasound findings of cholelithiasis with common bile duct dilation to 9mm. ERCP evaluation is recommended. General surgery has also been consulted for cholecystectomy planning.\n\nThank you,\nDr. John Smith',
    reviewedAt: d(22),
    createdAt: d(27),
    updatedAt: d(22),
  },

  // ── Rejected (1) ──────────────────────────────────────────────────────────
  {
    sessionId: 'ACI-008',
    providerName: 'Dr. Sarah Chen',
    patientId: 'PT-100002',
    patientName: 'Emily Rodriguez',
    patientDOB: new Date('1990-11-05'),
    patientInsurance: 'UnitedHealth',
    chiefComplaint: 'Skin rash',
    recordingDuration: 120,
    urgencyClassification: 'routine',
    audioTranscript: 'Patient Emily Rodriguez with a 2-week pruritic rash on both forearms. Appears erythematous with well-demarcated borders. Started after using a new laundry detergent. No systemic symptoms. No fever. Treated with topical hydrocortisone with minimal relief.',
    clinicalSummary: 'S: 34-year-old female with 2-week pruritic erythematous rash bilateral forearms following new detergent exposure. OTC hydrocortisone minimally effective.\nO: Well-demarcated erythematous plaques bilateral forearms. No vesicles. No systemic involvement.\nA: Allergic contact dermatitis.\nP: Switch to fragrance-free detergent, triamcinolone 0.1% ointment prescribed. Dermatology referral draft created but rejected — condition manageable in primary care.',
    referralNoteDraft: 'Dear Dermatology Colleague,\n\nI am referring Ms. Emily Rodriguez for evaluation of a 2-week contact dermatitis rash on bilateral forearms that has not responded to over-the-counter topical steroids.',
    urgencyReason: '',
    icdCodes: ['L23.7', 'L30.9'],
    recommendedSpecialty: 'Dermatology',
    status: 'rejected',
    reviewedAt: d(10),
    createdAt: d(14),
    updatedAt: d(10),
  },

  // ── Submitted (2) ─────────────────────────────────────────────────────────
  {
    sessionId: 'ACI-009',
    providerName: 'Dr. John Smith',
    patientId: 'PT-100005',
    patientName: 'David Lee',
    patientDOB: new Date('1955-01-30'),
    patientInsurance: 'Medicare',
    chiefComplaint: 'Hypertension follow-up',
    recordingDuration: 195,
    urgencyClassification: 'routine',
    audioTranscript: 'Patient David Lee follow-up for hypertension. Currently on lisinopril 20mg and amlodipine 10mg. BP today 162/98 despite maximal doses. Has been compliant with medications per refill records. No secondary causes worked up. 24-hour urine metanephrines and renal artery duplex pending. Nephrology referral warranted for resistant hypertension evaluation.',
    clinicalSummary: 'S: 70-year-old male with resistant hypertension. BP 162/98 on lisinopril 20mg and amlodipine 10mg at max doses. Medication compliant.\nO: BP 162/98 bilateral arms. No abdominal bruit. BMP: Cr 1.3, K 4.2. Echo: LVH. Renal artery duplex and 24-hr urine metanephrines pending.\nA: Resistant hypertension — secondary causes to be excluded.\nP: Nephrology referral; add chlorthalidone 25mg pending nephrology input.',
    referralNoteDraft: 'Dear Nephrology Colleague,\n\nI am referring Mr. David Lee, a 70-year-old male, for evaluation of resistant hypertension. Despite compliance with lisinopril 20mg and amlodipine 10mg at maximum doses, his blood pressure remains at 162/98 mmHg. He has LVH on echocardiogram and a creatinine of 1.3 mg/dL. Workup for secondary hypertension is underway including renal artery duplex and 24-hour urine metanephrines. Nephrology input on management and secondary cause evaluation is requested.\n\nThank you,\nDr. John Smith',
    urgencyReason: 'Resistant hypertension with LVH and CKD warrants nephrology evaluation for secondary cause identification.',
    icdCodes: ['I10', 'I51.7', 'N18.3'],
    recommendedSpecialty: 'Nephrology',
    status: 'submitted',
    approvedNote: 'Dear Nephrology Colleague,\n\nI am referring Mr. David Lee, a 70-year-old male, for evaluation of resistant hypertension. Despite compliance with lisinopril 20mg and amlodipine 10mg at maximum doses, his blood pressure remains at 162/98 mmHg. He has LVH on echocardiogram and a creatinine of 1.3 mg/dL. Workup for secondary hypertension is underway including renal artery duplex and 24-hour urine metanephrines. Nephrology input on management and secondary cause evaluation is requested.\n\nThank you,\nDr. John Smith',
    reviewedAt: d(18),
    createdAt: d(25),
    updatedAt: d(18),
  },
  {
    sessionId: 'ACI-010',
    providerName: 'Dr. Sarah Chen',
    patientId: 'PT-100004',
    patientName: 'Maria Garcia',
    patientDOB: new Date('1982-09-18'),
    patientInsurance: 'Cigna',
    chiefComplaint: 'Knee injury',
    recordingDuration: 240,
    urgencyClassification: 'emergent',
    audioTranscript: 'Patient Maria Garcia presents with acute right knee injury sustained during recreational soccer 4 hours ago. Immediate swelling and inability to bear weight. Positive Lachman test and positive anterior drawer. McMurray test positive medial compartment. Radiograph rules out fracture. Clinical picture consistent with ACL tear with possible medial meniscus injury.',
    clinicalSummary: 'S: 43-year-old female with acute right knee injury 4 hours ago during soccer. Immediate swelling, unable to bear weight.\nO: Significant knee effusion. Positive Lachman, positive anterior drawer, positive McMurray medial. XR: no fracture.\nA: Suspected ACL tear with concomitant medial meniscus injury — orthopedic surgery urgent referral.\nP: Knee immobilizer, crutches, ice elevation, MRI right knee ordered, orthopedic referral same-day.',
    referralNoteDraft: 'Dear Orthopedic Surgery Colleague,\n\nI am referring Ms. Maria Garcia, a 43-year-old female, for urgent evaluation of an acute right knee injury sustained 4 hours ago. Clinical examination reveals a positive Lachman test, positive anterior drawer, and positive McMurray test in the medial compartment, consistent with ACL tear and possible medial meniscus pathology. Radiograph has excluded fracture. An MRI of the right knee has been ordered. Same-day or next-day evaluation is requested.\n\nThank you,\nDr. Sarah Chen',
    urgencyReason: 'Acute ACL tear with suspected meniscus injury requires same-day orthopedic evaluation for surgical planning and joint stability assessment.',
    icdCodes: ['S83.511A', 'S83.201A', 'M23.200'],
    recommendedSpecialty: 'Orthopedic Surgery',
    status: 'submitted',
    approvedNote: 'Dear Orthopedic Surgery Colleague,\n\nI am referring Ms. Maria Garcia, a 43-year-old female, for urgent evaluation of an acute right knee injury sustained 4 hours ago. Clinical examination reveals a positive Lachman test, positive anterior drawer, and positive McMurray test in the medial compartment, consistent with ACL tear and possible medial meniscus pathology. Radiograph has excluded fracture. An MRI of the right knee has been ordered. Same-day or next-day evaluation is requested.\n\nThank you,\nDr. Sarah Chen',
    reviewedAt: d(28),
    createdAt: d(30),
    updatedAt: d(28),
  },
];

async function seedAmbientSessions() {
  try {
    const count = await AmbientSession.countDocuments();
    if (count > 0) {
      console.log(`AmbientSession collection already has ${count} records — skipping seed.`);
      return;
    }
    await AmbientSession.insertMany(sampleSessions);
    console.log(`AmbientSession: seeded ${sampleSessions.length} sample records.`);
  } catch (err) {
    console.error('AmbientSession seed error:', err.message);
  }
}

module.exports = { seedAmbientSessions };
